### ISSUE TITLE
Code Smells Review

### ISSUE THREAD

**Issue by bkromrey** [hoobhab/jsonexporter#1]
**Code Smells - Commented-Out Code**

In `emailer.py` on lines 36-38 you have a commented out "sample" of how to use the code. This would be better suited for the README to reduce confusion within the code itself.

**Code Smells - Long Function**

The `exportPdf` function in `jsonexporter.py` is a bit long - you could probably combine a lot of these lines to reduce the length.

Additionally the `sendMail` function in `emailer.py` is also a long function.

**Code Smells - Duplicate Code**

Lines 4-9 on `jsonexporter.py` import unused libraries (I think you moved these to a separate `emailer.py` file).

**Code Smells - Long Lines**

In `emailer.py` your docstring on line 13 is very long. You might want to add some carriage returns to make it easier to read. 

Additionally, in `jsonexporter.py`, lines 27, 52, and 54 are all pretty lengthy.

**Comment by hoobhab** [comment]
Sample code in emailer.py moved to the readme. Long lines reduced.
