### ISSUE TITLE
Microservice Should Be Passed JSON Object, Not JSON File

### ISSUE THREAD

**Issue by bkromrey** [hoobhab/jsonexporter#6]
Per [Ed Discussion Post](https://edstem.org/us/courses/64483/discussion/5635701) we should be passing the JSON as an object instead of as a file.

JSON object will follow the same format as the contents of the sample JSON file.

**Comment by hoobhab** [comment]
The packing list imported into the microservice is now a JSON object instead of the string of the filename. Readme has been updated as well.
